spring.config.import=optional:classpath:secrets.properties
server.port=8080
# ==========================================
# DATABASE CONNECTION
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/airport_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SECURITY: Pulled dynamically from the .env file
spring.datasource.password=abdalla

# ==========================================
# JPA / HIBERNATE SETTINGS
# ==========================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update

# ==========================================
# SECURITY SETTINGS
# ==========================================
# SECURITY: Pulled dynamically from the .env file
jwt.secret=9a6142a78f654b9f9d2d4b7f8e1a6d3c5f9a6142a78f654b9f9d2d4b7f8e1a6d3c
jwt.expiration=86400000 
# (Expiration is set to 24 hours in milliseconds)