spring.datasource.url=jdbc:h2:mem:airport_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true

jwt.secret=9a6142a78f654b9f9d2d4b7f8e1a6d3c5f9a6142a78f654b9f9d2d4b7f8e1a6d3c
jwt.expiration=86400000
